# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13CGxZGasR5cjv7nI2w4WUKzHExdi2bGc
"""

!pip install -q pyngrok
!pip install -q streamlit
!pip install -q streamlit_ace
!pip install fuzzywuzzy[speedup]
!streamlit run app.py & > / dev / null &

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import json
# import requests as req
# from fuzzywuzzy import process
# from fuzzywuzzy import fuzz
# from pyngrok import ngrok
# 
# def main():
#     html_temp = """ <div style ="background-color:blue;padding:13px">
#                       <h1 style = "color:white;text-align:center;">Ola parceiro, publique seus itens</h1>
#                     </dic>
#                 """
#     st.markdown(html_temp, unsafe_allow_html = True)
#     item = st.text_input("item")
# 
#     def verificarNome(item):
#       res = req.get("https://kndhvh.github.io/eleicao.json")
#       dict = res.json()['eleicao']
#       lista_fuzy = process.extract(item,dict,scorer=fuzz.token_sort_ratio)
#       resultado = []
#       for sublinha in lista_fuzy:
#         if sublinha[1]> 50:
#           resultado.append(sublinha)
#       if len(resultado) >= 1:
#         st.warning("Atencao as fake news")
#       else:
#         st.success("Liberado")
# 
#     if st.button("Verificar"):
#       verificarNome(item)
# if __name__=='__main__':
#   main()

!streamlit run app.py & npx localtunnel --port 8501